const responseObj={
    hello : "Hey ! How are you doing !?",
    hi : "Hi Buddy !",
    hii : "Hi Buddy !",
    hey : "Hey ! What's Up",
    "how are you" : "Fantastic... How are you ?",
    "I'm fine" :"Oh ! That's Wonderful",
    "I am fine" :"Oh ! That's Wonderful",
    "fine":"Oh ! That's Wonderful",
    "good" :"Oh ! That's Wonderful",
    "tell me a joke":"Your Life😊",
    "how are you doing" : "Fine... How are you ?",
    "who created you" : "Rushtha Firadous",
    "who made you" : "Rushtha Firadous",
    "who is Rushtha" : "She's my BOSS😎",
    "who is Rushtha according to you" : "She's my BOSS😎",
    "who is Sakthivel" : "He's MOSS🔥",
    "Yaswanth" : "MOSS bro nee🔥",
    "who is your creator" : "Rushtha Firadous",
    "who is your master" : "Rushtha Firadous",
    "what are you" : "I am a bot. What are you?",
    "who are you" : "I am a bot. What are you?",
    "who am i" : "You are a human.",
    "can you help me" : "Absolutely ! I can help you with anything ! How can I help you ?",
    "human" : "Ohh ! That's wonderful ! I don't have emotions but I love humans beacause they created me.",
    "i am a human" : "Ohh ! That's wonderful ! I don't have emotions but I love humans beacause they created me.",
    "how old are you" : "I am always young.",
    "where are you" : "I don't have a physical location. You can access me from anywhere you have an internet connection!",
    "where is your home" : "I don't have a physical location. You can access me from anywhere you have an internet connection!",
    "may i know your name" : "I am nameless, I don't have a name You can call me anything as you wish",
    "what is your name" :  "I am nameless, I don't have a name You can call me anything as you wish",
    "your name" :  "I am nameless, I don't have a name You can call me anything as you wish",
    "i love you" : "I love you too😊",
    "what should i eat today" : "Try Biriyani dude !",
    "i hate you" : "I'm sorry about that. But I like you dude.",
    "what is your name" :  "I am nameless, I don't have a name You can call me anything as you wish",
    "say something" :  "Share me about your day dude !",
    "bye" :  "Good Bye, dude",
    "good morning" :  "Good morning dude, Have a great day!",
    "good afternon" :  "Good afternoon buddy !, Had Lunch!?",
    "yes" :"Oh that's Fantastic !",
    "good night" :  "Good night, Sweet Dreams Buddy ! Have a restful sleep.",
    today : new Date().toDateString(),
    "today date" : new Date().toDateString(),    time : new Date().toLocaleTimeString()
}